import JSZip from 'jszip'
import type { Project } from '@/types/database'

interface ZipInput {
  project: Project
  results: {
    favicons: Record<string, Buffer> | null
    ogImages: Record<string, Buffer> | null
    appIcons: Record<string, Buffer> | null
    splashScreens: Record<string, Buffer> | null
    pwaManifest: Record<string, Buffer> | null
    codeSnippets: Record<string, Buffer> | null
  }
}

export async function createZip(input: ZipInput): Promise<Buffer> {
  const { project, results } = input
  const zip = new JSZip()
  const pwaIconFilenames = new Set(['icon-192.png', 'icon-512.png'])

  function addFiles(folder: JSZip, files: Record<string, Buffer>) {
    for (const [filename, buffer] of Object.entries(files)) {
      folder.file(filename, buffer)
    }
  }

  if (results.favicons) {
    const faviconFiles = Object.fromEntries(
      Object.entries(results.favicons).filter(([filename]) => !pwaIconFilenames.has(filename))
    )
    addFiles(zip.folder('web/favicons')!, faviconFiles)
  }

  if (results.ogImages) {
    addFiles(zip.folder('web/og-images')!, results.ogImages)
  }

  if (results.pwaManifest) {
    const pwaFolder = zip.folder('web/pwa')!
    addFiles(pwaFolder, results.pwaManifest)

    if (results.favicons) {
      const pwaIcons = Object.fromEntries(
        Object.entries(results.favicons).filter(([filename]) => pwaIconFilenames.has(filename))
      )
      addFiles(pwaFolder, pwaIcons)
    }
  }

  if (results.appIcons) {
    addFiles(zip.folder('mobile/icons')!, results.appIcons)
  }

  if (results.splashScreens) {
    addFiles(zip.folder('mobile/splash')!, results.splashScreens)
  }

  if (results.codeSnippets) {
    addFiles(zip.folder('code-snippets')!, results.codeSnippets)
  }

  zip.file('README.md', generateReadme(project))

  const buffer = await zip.generateAsync({ type: 'nodebuffer' }) as Buffer
  return buffer
}

function generateReadme(project: Project): string {
  return `# ${project.name} - Brand Assets

Generated by BrandKit

## Contents

- **web/favicons/** - Favicon (SVG, PNG, ICO)
- **web/og-images/** - OG Image & Twitter Card
- **web/pwa/** - PWA Manifest + PWA Icons
- **mobile/icons/** - iOS/Android App Icons
- **mobile/splash/** - Splash Screens
- **code-snippets/** - Framework-specific snippets

## Usage

Copy the assets to your project's public directory and use the code snippets for integration.

---

Generated on ${new Date().toISOString()}`
}
