import JSZip from 'jszip'
import type { Project } from '@/types/database'

interface ZipInput {
  project: Project
  results: {
    favicons: Record<string, Buffer> | null
    ogImages: Record<string, Buffer> | null
    appIcons: Record<string, Buffer> | null
    splashScreens: Record<string, Buffer> | null
    pwaManifest: Record<string, Buffer> | null
    codeSnippets: Record<string, Buffer> | null
  }
}

export async function createZip(input: ZipInput): Promise<Buffer> {
  const { project, results } = input
  const zip = new JSZip()

  function addFiles(folder: JSZip, files: Record<string, Buffer>) {
    for (const [filename, buffer] of Object.entries(files)) {
      folder.file(filename, buffer)
    }
  }

  if (results.favicons) addFiles(zip.folder('web/favicons')!, results.favicons)
  if (results.ogImages) addFiles(zip.folder('web/og-images')!, results.ogImages)
  if (results.pwaManifest) addFiles(zip.folder('web/pwa')!, results.pwaManifest)
  if (results.appIcons) addFiles(zip.folder('mobile/icons')!, results.appIcons)
  if (results.splashScreens) addFiles(zip.folder('mobile/splash')!, results.splashScreens)
  if (results.codeSnippets) addFiles(zip.folder('code-snippets')!, results.codeSnippets)

  zip.file('README.md', generateReadme(project))

  return await zip.generateAsync({ type: 'nodebuffer' }) as Buffer
}

function generateReadme(project: Project): string {
  return `# ${project.name} - Brand Assets

Generated by BrandKit

## Contents

- **web/favicons/** - Favicon (SVG, PNG, ICO)
- **web/og-images/** - OG Image & Twitter Card
- **web/pwa/** - PWA Manifest
- **mobile/icons/** - iOS/Android App Icons
- **mobile/splash/** - Splash Screens
- **code-snippets/** - Framework-specific snippets

## Usage

Copy the assets to your project's public directory and use the code snippets for integration.

---

Generated on ${new Date().toISOString()}`
}
